---
title: TRY data summary
author: Alexey Shiklomanov
output: 
    html_document:
        toc: true
        theme: united
---

```{r setup, echo = FALSE, results = 'hide'}
library(tidyverse)
traits_pfts <- readRDS('traits_pfts.rds')
all_pfts <- readRDS('all_pfts.rds')
species_phylo <- src_sqlite('try.sqlite') %>% 
    tbl('species_phylo') %>% 
    collect(n = Inf)
traits_phylo <- traits_pfts %>% 
    left_join(species_phylo)
pfts_phylo <- all_pfts %>% 
    left_join(species_phylo)
```

# Phylogeny

## Observations, by missing vs. nonmissing family
```{r rowsbymissingfamily}
traits_phylo %>% 
    count(is.na(Family)) %>% 
    knitr::kable()
```

## Number of observations, by Family
```{r rowsbyfamily}
traits_phylo %>% 
    count(Family, sort = TRUE) %>% 
    head(20) %>% 
    knitr::kable()
```

## Observations missing family, by species
```{r missingfamilybyspecies}
traits_phylo %>% 
    filter(is.na(Family)) %>% 
    count(AccSpeciesID, AccSpeciesName, sort = TRUE) %>% 
    head(20) %>% 
    knitr::kable()
```

# Traits

## Number of observations (rows), by PFT

```{r rowsbypft}
traits_pfts %>% 
    count(pft, sort = TRUE) %>% 
    knitr::kable()
```

## Non-missing traits by PFT

```{r nonmissingbypft}
traits_pfts %>% 
    group_by(pft) %>% 
    summarize_at(vars(-ObservationID, -AccSpeciesID),
                 (function(x) sum(!is.na(x)))) %>% 
    knitr::kable()
```

## Non-missing traits by family

```{r missingbyfamily}
traits_phylo %>% 
    group_by(Family) %>% 
    summarize_if(is_double,
                 (function(x) sum(!is.na(x)))) %>% 
    mutate(total = rowSums(.[-1])) %>% 
    select(Family, total, everything()) %>% 
    arrange(desc(total)) %>% 
    head(25) %>% 
    knitr::kable()
```

# PFTs 

## Species missing PFTs, by attribute

```{r pftsnonmissingcategory}
all_pfts %>% 
    filter(is.na(pft)) %>% 
    count(leaf_type, phenology, ps_pathway, growth_form, woodiness, climate_zone, sort = TRUE) %>% 
    head(15) %>% 
    knitr::kable()
```

## Species, by missing vs. nonmissing PFT

```{r speciesmissingpft}
all_pfts %>% count(is.na(pft)) %>% knitr::kable()
```

## Species, by PFT (including missing)

```{r speciesbypft}
count(all_pfts, pft, sort = TRUE) %>% knitr::kable()
```

# Plots and summaries 

```{r datasummary}
cpdat <- readRDS('traits_analysis.rds')
sumlong <- cpdat %>% 
    select(which(sapply(., is_double))) %>% 
    gather() %>% 
    group_by(key) %>% 
    summarize(min = min(value, na.rm = TRUE),
              max = max(value, na.rm = TRUE),
              mean = mean(value, na.rm = TRUE),
              median = median(value, na.rm = TRUE))
knitr::kable(sumlong)
```

```{r covariances, fig.height=12, fig.width=10}
traits_nested <- cpdat %>% 
    select(pft, which(sapply(., is_double))) %>% 
    nest(-pft)
covdat <- traits_nested %>% 
    mutate(covmat = map(data, cov, use = 'pairwise.complete.obs'),
           cormat = map(covmat, cov2cor))
covmat2df <- function(mat) {
    mat2 <- mat
    mat2[upper.tri(mat2, diag = TRUE)] <- NA
    long <- reshape2::melt(mat2) %>% 
        as_data_frame %>% 
        mutate(cor_vars = paste(Var1, Var2, sep = '.'),
               value = if_else(abs(value) > 1, NA_real_, value)) %>% 
        filter(!is.na(value)) %>% 
        filter(!grepl('area.*mass|mass.*area', cor_vars),
               !grepl('SLA\\.LMA|LMA\\.SLA', cor_vars)) %>% 
        select(-Var1, -Var2)
    return(long)
}

covdat_long <- covdat %>% 
    mutate(cor_long = map(cormat, covmat2df))

cor_unnest <- covdat_long %>% 
    select(pft, cor_long) %>% 
    unnest()

ggplot(cor_unnest %>% filter(!is.na(pft))) + 
    aes(x = pft, y = value, fill = pft) +
    geom_col(position = 'dodge') + 
    facet_wrap(~cor_vars, scales = 'free_x') + 
    theme(axis.text.x = element_blank(), 
          legend.position = 'bottom')
```

```{r correlationplots, fig.width=10}
xy_plot2 <- function(x, y) {
    xexp <- parse(text = x)
    yexp <- parse(text = y)
    plt_dat <- filter(cpdat, !is.na(eval(xexp)), !is.na(eval(yexp)))
    plt <- ggplot(plt_dat) + 
        aes_string(x = sprintf('log(%s)', x), y = sprintf('log(%s)', y)) +
        aes(color = pft) + 
        geom_point(size = 0.5, alpha = 0.2) + 
        geom_smooth(method = 'lm', se = FALSE) + 
        theme(legend.position = 'bottom')
    plot(plt)
}

expand_nonrep <- . %>% combinat::combn(2) %>% t() %>% as_data_frame()
mass_vars <- c('leaf_lifespan', 'SLA' ,'Nmass', 'Pmass', 'Rdmass', 'Vcmax_mass', 'Jmax_mass')
mass_df <- expand_nonrep(mass_vars)
area_vars <- c('leaf_lifespan', 'LMA' ,'Narea', 'Parea', 'Rdarea', 'Vcmax_area', 'Jmax_area')
area_df <- expand_nonrep(area_vars)

for (i in seq_len(nrow(mass_df))) xy_plot2(mass_df[[i,1]], mass_df[[i,2]])
for (i in seq_len(nrow(area_df))) xy_plot2(area_df[[i,1]], area_df[[i,2]])
```
